[package]
name = "oktypes"
version = "0.1.0"
edition = "2018"

[dependencies]
tree-sitter = "0.20.0"
tree-sitter-kotlin = { git = "https://github.com/rsookram/tree-sitter-kotlin", rev = "72fdb14af0c2d63dca842026d76799d7015aeb71" }
rayon = "1.5.1"

[profile.release]
lto = true
codegen-units = 1
